# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

# Development dependencies
group :development do
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'yard'
end

# Test dependencies
group :test do
  gem 'minitest'
end

# Build and development tools
group :development, :test do
  gem 'bundler'
  gem 'rake'
end
