#!/usr/bin/env bash
# Supex test runner
set -e

SCRIPT_PATH="${BASH_SOURCE[0]}"
while [ -L "$SCRIPT_PATH" ]; do
  SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
  [[ "$SCRIPT_PATH" != /* ]] && SCRIPT_PATH="$SCRIPT_DIR/$SCRIPT_PATH"
done
SUPEX_ROOT="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"

exec "$SUPEX_ROOT/scripts/launch-test.sh" "$@"
