# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

# Development dependencies
group :development do
  gem 'minitest'
  gem 'rake'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'yard'
end
